### ISSUE TITLE
PTZ with WebRTC-Camera preview

### ISSUE THREAD

**Issue by mikigal** [user2684/imou_life#131]
## Version of the custom_component 1.0.15

I'm trying to get PTZ working with local stream based on WebRTC Camera integration (using go2rtc). I got PTZ layout, but it does nothing. I won't use preview from Imou API due to limited requests to API.
How can do I it? I'm sure [imouapi](https://github.com/user2684/imouapi) can control this camera as I tested in in CLI mode.

### What I did

```
type: grid
square: false
columns: 1
cards:
  - type: entities
    entities:
      - entity: sensor.przed_domem_status
        name: Stan
  - type: custom:webrtc-camera
    url: >-
      rtsp://admin:*censored*@10.10.10.21/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46YWRtaW4=
    muted: true
    intersection: 1
    ui: true
    device_id: *censored*
    ptz:
      service: imou_life.ptz_move
      device_id: *censored*
      data_left:
        device_id: *censored*
        duration: 100
        operation: LEFT
      data_right:
        device_id: *censored*
        duration: 100
        operation: RIGHT
      data_up:
        device_id: *censored*
        duration: 100
        operation: UP
      data_down:
        device_id: *censored*
        duration: 100
        operation: DOWN
      data_zoom_in:
        device_id: *censored*
        duration: 100
        operation: ZOOM_IN
      data_zoom_out:
        device_id: *censored*
        duration: 100
        operation: ZOOM_OUT

```

## Debug log

There's no any information/errors in logs

![preview](https://github.com/user-attachments/assets/e217d471-0585-47cd-b036-ac91f508ec89)
