### ISSUE TITLE
PTZ control to move the camera :)

### ISSUE THREAD

**Issue by mabusdogma** [user2684/imou_life#17]
Hello, I have an Imou Ranger 2 camera and it works well on Home Assistant, even more since this integration, but I would like to ask for PTZ control.
There are some camera integrations that allow to add PTZ controls and move it at will from HA.
(example: https://github.com/AlexxIT/WebRTC/wiki/PTZ-Config-Examples)

Now I can open and close the camera from Home Assistant, and that's a big step to automate the cameras.
Would you consider to add PTZ control to imou based cameras?

Thanks in advance

**Comment by user2684** [comment]
Hi, yes, theoretically is possible, Imou esposes API for controlling the camera. Adding it to the roadmap. Out of curiosity, does the onvif integration already support it? Just to avoid duplicated functionalities :-)

**Comment by mabusdogma** [comment]
I've been trying to have a PTZ control and as far as I know... No, it's not supported, at least not for the Imou Ranger 2.

**Comment by rogodra** [comment]
From what I tested, with onvif PTZ control is not possible.
Now I can get my two Imou Ranger 2 out of the drawer.
Thanks for the work!

**Comment by user2684** [comment]
Ok, let me then have a look at this in the medium term. Do you have by chance any examples of other webcams in HA which has this PTZ control capability? Just to understand how to then represent it in HA :-)
THanks

**Comment by rogodra** [comment]
I also have Tapo brand cameras, and they allow you to move the camera with arrows. These cameras allow from the official app to mark fixed positions, which from HA you can tell to go to the current PTZ position at a preset value.

I don't know if there would also be an option to tell the camera to go to a preset PTZ position.

I leave you the integration link.
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control

Thanks

**Comment by user2684** [comment]
Thanks, I will have a look at it so to have a consistent implementation in HA :-)

**Comment by Andreastap** [comment]
integrate the ptz would be a great thing, I hope you succeed thanks to the work you've done so far.

**Comment by user2684** [comment]
Hi, what's your view on https://community.home-assistant.io/t/imou-life-cloud-integration/462439/106? Thanks :-)

**Comment by user2684** [comment]
Implemented in 1.0.9

**Comment by mabusdogma** [comment]
Works great! I use the [WebRTC Integration](https://github.com/AlexxIT/WebRTC) for the Imou camera (no lag, no ONVIF integration needed) so if you want to add PTZ control inside the camera image, you can do this:
![image](https://user-images.githubusercontent.com/19146242/204111857-e8afad84-4038-493d-8685-f9e060afc240.jpg)


a) Install the WebRTC integration
b) create a new configuration card
c) add this (replacing with your device ID, secretkey and IP)

```
type: custom:webrtc-camera
url: rtsp://admin:secretkey@IP:554/cam/realmonitor?channel=1&subtype=1
muted: false
intersection: 1
ui: true
device_id: <your device ID>
ptz:
  service: imou_life.ptz_move
  data_left:
    device_id: <your device ID>
    duration: 100
    operation: LEFT
  data_right:
    device_id: <your device ID>
    duration: 100
    operation: RIGHT
  data_up:
    device_id: <your device ID>
    duration: 100
    operation: UP
  data_down:
    device_id: <your device ID>
    duration: 100
    operation: DOWN
  data_zoom_in:
    device_id: <your device ID>
    duration: 100
    operation: ZOOM_IN
  data_zoom_out:
    device_id: <your device ID>
    duration: 100
    operation: ZOOM_IN


```
