### ISSUE TITLE
Unique Callback URL for each device

### ISSUE THREAD

**Issue by jrb80** [user2684/imou_life#31]
The Callback URL is not unique for each device.  If I set the URL on camera 1 and then set the URL on camera 2, the URL from camera 2 is then applied to camera 1.  I would have expected the URL for camera 1 to be retained and not overwritten by camera 2. It appears to be a global setting.

My intention is to create template sensors for each camera (webhook), this could make it easier to integrate the webhook events. Below is an example of what could be achieved.

However, I suspect this is not possible as the Callback URL is linked to the developer account which only allows one Callback address per account https://open.imoulife.com/book/http/push/setMessageCallback.html

```
template:
  - trigger:
      - platform: webhook
        webhook_id: imou_life_webhook_1
    sensor:
      - name: "Imou cName"
        state: "{{ trigger.json.cname }}"
      - name: "Imou deviceType"
        state: "{{ trigger.json.deviceType }}"
      - name: "Imou msgType"
        state: "{{ trigger.json.msgType }}"
      - name: "Imou labelType"
        state: "{{ trigger.json.labelType }}"
```
