### ISSUE TITLE
Errors on a VERSA cam (IPC-C22FP-C) of two installed

### ISSUE THREAD

**Issue by fbertelli** [user2684/imou_life#51]
## Version of the custom_component

HACS imou 1.0.12

## Configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Logger
logger:
  default: critical
  logs:
    custom_components.imou_life: debug
    imouapi: debug
    
```

## Describe the bug

Hi All,
first of all, I'm sorry for my english! :)
I have 2 VERSA cam installed in my home. 
I tried to integrate them into HA: for one of them (called "Soggiorno") all was ok.
For the other one (called "Camera Piccola") I have many issues:

- Aspect ratio is wrong (as you can see in the first image below)
- When I open the "stream", it is freezed with the "loading" circle in the middle, and a quick and flashing error message on the top (you can see in the second image, I was able to catch it)

I enabled the SD stream for "Camera Piccola" cam and the "playback" is ok, but the aspect ratio is still wrong.

In the IMOU app I have no problem: playback is ok and aspect ratio is the same of "Soggiorno" cam.

Sometimes I have a gray image in the HA dashboard for "Camera Piccola" preview (both HD and SD, but not in the same time - IMAGE 3 below)

Below you can find the logs of HA after a restart and some tests on camera.

Please, help me in order to solve these issues.

Thanks

IMAGE 1
![image](https://user-images.githubusercontent.com/58268853/219794623-44293e20-2fc3-41b0-b964-a0dffce41bd8.png)

IMAGE 2
![image](https://user-images.githubusercontent.com/58268853/219797133-6dd7b8f7-de8f-4cb8-86b8-fd043b9c1a63.png)

IMAGE 3
![image](https://user-images.githubusercontent.com/58268853/219798490-a7dc0176-6405-4f11-8949-c6724d1c4d2c.png)

## Debug log

```text

[home-assistant.log](https://github.com/user2684/imou_life/files/10771889/home-assistant.log)


```
