### ISSUE TITLE
Can't get usable image via "picUrl" or "thumbUrl"

### ISSUE THREAD

**Issue by kerryland** [user2684/imou_life#66]
Motion-triggered callbacks contain a **"picUrl"** link to an image (or maybe video?), which I would *love* to make use of:
```
trigger:
  platform: webhook
  webhook_id: imou_life_callback_12345
  json:
    deviceType: IPC
    msgType: human
    cname: Driveway
    labelType: humanAlarm
   <snip>
    picUrl:
      - >-
        https://cloudreadproxy-online-sgedge.imoulife.com:27216/6E09A42PAZ645FC_img/Alarm/0/3d42f60f6e1e4427b549290b33e52630_big_0_thumb_qcif.dav?sig=jgmqNtLj9/qbVWP9ckTBT6wSfNoai1rf09GsmXerliQ=&e=1688518125&v=v1&t=r&time=20230704004845
```
...but it appears to be a ".dav" file, and I can't find a way to turn that into anything useful (jpeg or png or mp4 -- anything!)

The human-detection isn't very good in the rain, so I want to send the image to deepstack for some higher quality analysis. Currently I am making a call to the generic "camera.snapshot" method, but it fires a few seconds after motion is detected, so is often too late to see anything :-(

Any ideas on how to access this image?
