### ISSUE TITLE
Imou life motion detection (Option 3) automation error

### ISSUE THREAD

**Issue by sominaik** [user2684/imou_life#71]
## Version of the custom_component
1.0.13

## Configuration

```yaml
Logger: homeassistant.helpers.template
Source: helpers/template.py:233
First occurred: September 5, 2023 at 10:51:55 PM (4 occurrences)
Last logged: 5:43:11 PM

Template variable error: 'dict object' has no attribute 'json' when rendering '{% for entity_name in integration_entities("imou_life") %} {%- if entity_name is match('.+_refreshalarm$') and is_device_attr(entity_name, "hw_version", trigger.json.did) %} {{entity_name}} {%-endif%} {%- endfor %}'
```

## Describe the bug

I am having an error in the automation which I pasted from the repo. Tried to call the service manually to refresh alarm and it works. Just that automation is not kicking in

## Debug log

```text
![ImouIssue](https://github.com/user2684/imou_life/assets/69377651/683fad34-2665-4d2b-88f2-e9921f2aca8a)
Is the above error good enough to guide?
```
