### ISSUE TITLE
APIError: FL1001: Insufficient remaining available licenses

### ISSUE THREAD

**Issue by scannifn** [user2684/imou_life#77]
## Configuration
**Core 2023.11.3
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2**

```yaml
Logger: custom_components.imou_life
Source: custom_components/imou_life/entity.py:81
Integration: Imou Life (documentation, issues)
First occurred: 18:47:28 (10 occurrences)
Last logged: 18:47:30

APIError: FL1001: Insufficient remaining available licenses, please contact platform customer service. Traceback (most recent call last): File "/config/custom_components/imou_life/entity.py", line 79, in async_added_to_hass await self.sensor_instance.async_update() File "/usr/local/lib/python3.11/site-packages/imouapi/device_entity.py", line 128, in async_update data = await self.api_client.async_api_deviceSdcardStatus(self._device_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 466, in async_api_deviceSdcardStatus return await self._async_call_api(api, payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 216, in _async_call_api raise APIError(error_message) imouapi.exceptions.APIError: FL1001: Insufficient remaining available licenses, please contact platform customer service.
APIError: FL1001: Insufficient remaining available licenses, please contact platform customer service. Traceback (most recent call last): File "/config/custom_components/imou_life/entity.py", line 79, in async_added_to_hass await self.sensor_instance.async_update() File "/usr/local/lib/python3.11/site-packages/imouapi/device_entity.py", line 294, in async_update data = await self.api_client.async_api_getDeviceCameraStatus(self._device_id, self._name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 343, in async_api_getDeviceCameraStatus return await self._async_call_api(api, payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 216, in _async_call_api raise APIError(error_message) imouapi.exceptions.APIError: FL1001: Insufficient remaining available licenses, please contact platform customer service.
```

## Describe the bug
Starting from 6th November 2 cameras are not visible anymore.

![image](https://github.com/user2684/imou_life/assets/67062892/9023b291-6dc0-431b-a53f-730e9920222e)

I have checked in https://open.imoulife.com/consoleNew/vas/deviceIn but I do not see licenses exceeded

![image](https://github.com/user2684/imou_life/assets/67062892/f1a5588d-56de-4012-8fec-88327e881d89)
